### ISSUE TITLE
The package is missing io.vertx.di.foo.reactivex

### ISSUE THREAD

**Issue by jcalvopinam** [FrederikS/vertx-dependency-injection#1]
Hi,

Thanks for the article, is interesting!

I have cloned your project to try to understand better your implementation and I noticed that the class from `service-proxy/src/main/java/io/vertx/di/MainVerticle.java` has the following import `io.vertx.di.foo.reactivex.FooRepository;` that not found

maybe you forgot to upload the package with that class?

The implementation is different according to the others classes. `FooRepository` this seems to have a constructor and a method called `rxSave`

It is not possible to reproduce the example with vertx service proxy.
Could you check it please?

Thanks

**Comment by FrederikS** [comment]
Hi @juanca87, thanks for you interest.

This `reactivex.FooRepository` implementation will be generated during the build process. So it should be in place after executing `./gradlew build`.

**Comment by jcalvopinam** [comment]
Hello @FrederikS

I had not realized that. In fact, after compiling, the implementation was generated.
Thanks for clarifying it!
